### ISSUE TITLE
how to get Lndmobile.aar source code?

### ISSUE THREAD

**Issue by gosgos11** [synonymdev/react-native-lightning#27]

**Comment by losh11** [comment]
The Lndmobile framework is generated by doing `make android` in lnd source. You can read more about building mobile frameworks & how to setup in: [lnd/mobile](https://github.com/lightningnetwork/lnd/blob/master/mobile/README.md)

**Comment by gosgos11** [comment]
> The Lndmobile framework is generated by doing `make android` in lnd source. You can read more about building mobile frameworks & how to setup in: [lnd/mobile](https://github.com/lightningnetwork/lnd/blob/master/mobile/README.md)

Thank you reply so quickly. I will try the lnd/mobile.
