### ISSUE TITLE
Error (iOS & Android): `new NativeEventEmitter()` requires a non-null argument

### ISSUE THREAD

**Issue by coreyphillips** [synonymdev/react-native-lightning#28]
Steps to Reproduce:
 - `react-native init lightningtest && cd lightningtest && yarn install && yarn add @synonymdev/react-native-lightning &&  cd ios && pod install && cd ../`
 - Add the following line to the top of `App.js`:
    - `import lndCache from '@synonymdev/react-native-lightning/dist/utils/neutrino-cache';`
 - `react-native run-ios`

Expected Behavior:
 - The app builds and runs as expected without errors.

Actual Behavior:
 - The app fails to build and the following error is returned:
   - Error (iOS & Android): `new NativeEventEmitter()`

RN Version Info:
```
"react": "17.0.2",
"react-native": "0.66.3",
```

**Comment by hsjoberg** [comment]
I believe this should work, but it looks like you solved it in another way.

https://github.com/hsjoberg/blixt-wallet/blob/5b9f92ce6bdcb365ac6f59406f292d5309f727b9/src/utils/event-listener.ts
